<-GameWidget>:
    PlayerZone:
        id: player_zone
    MainZone:
        id: main_zone

<MainZone@RelativeLayout>:
    size_hint: 1, 0.7
    pos_hint: {'x': 0.0, 'y': 0.15}
    canvas.before:
        Color:
            rgba: 0.0, 1, 0.0, 0.3
        Rectangle:
            pos: self.pos
            size: self.size

<PlayerZone@TabbedPanel>
    size_hint: 1, 0.3
    tab_height: 20
    do_default_tab: False

