<-CardWidget>:
    size_hint: (None, 1) 
    width: 70
    on_card: name.text = self.card.name
    drag_rectangle: self.x, self.y, self.width, self.height

    drag_timeout: 10000000
    drag_distance: 0

    canvas.before:
        Color:
            rgb: 0, 0.0, 0.8
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        id: name
        text: ""
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
#        pos: root.pos
