<-CardWidget>:
    size_hint: 0.2, 0.4
    on_card: name.text = self.card.name
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000000
    drag_distance: 0
    canvas.before:
        Color:
            rgb: 0.5, 0.5, 0.5
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        id: name
        text: ""
        pos_hint: {'x': 0.0, 'y': 0.0}
#        pos: root.pos